### ISSUE TITLE
Game startup crash with newer CreativeCore version (Fabric)

### ISSUE THREAD

**Issue by Denisgamer11** [CreativeMD/EnhancedVisuals#132]
Game is able to boot with CreativeCore_FABRIC_v**2.10.24**_mc1.20.1 but does not work with CreativeCore_FABRIC_v**2.11.9**_mc1.20.1 or newer. 

AmbientSounds and FallingTree requires 2.11.9 so I cannot run both of these mods

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-04-23 21:05:25
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'enhancedvisuals'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void team.creative.creativecore.common.network.CreativeNetwork.<init>(java.lang.String, org.apache.logging.log4j.Logger, net.minecraft.class_2960)'
	at team.creative.enhancedvisuals.EnhancedVisuals.<clinit>(EnhancedVisuals.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
```

**Comment by CreativeMD** [comment]
AmbientSounds works with the newer version as well (if you get the newest). I don't think FallingTree requires CreativeCore at all.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it is still not solved report back here.
